version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - 8000:8000

  llm-rag:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chromadb
    env_file:
      - .env
    volumes:
      - ./models/GPTS:/app/models # LLM (from outside model to container)
      - ./hf-models:/root/.cache/huggingface # HF Embedder or other stuff (from container cache to outside) # doesnt work
    ports:
      - 9000:9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

volumes:
  index_data: