version: '3.7'

services:
  llm-postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: $POSTGRES_HOST
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  llm-backend:
    build:
      context: model-backend
      dockerfile: Dockerfile
    depends_on:
      - chromadb
    restart: always
    env_file:
      - ./model-backend/.env
    volumes:
      - ./hf-models:/root/.cache/huggingface
    ports:
      - '9000:9000'

  backend-app:
    build:
      context: backend/
      dockerfile: Dockerfile
    depends_on:
      - llm-postgres
      - llm-backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: sh -c "./entrypoint.sh"
    restart: always

  client-app:
    build:
      context: client/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend-app
    ports:
      - '5173:5173'
    command: ['npm', 'run', 'dev']
    restart: always

  llm-redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - 8000:8000

volumes:
  pg_data:
