# Generated by Django 5.0.3 on 2024-03-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptionlevel'),
        ),
    ]
