# Generated by Django 5.0.3 on 2024-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='icon',
            field=models.ImageField(blank=True, upload_to='collections/icons'),
        ),
    ]
